/**
 * Terraform wrapper — generates _backend.tf and _provider.tf from .as.yml
 * conventions, then runs terraform directly. Replaces Terragrunt.
 */

import { writeFileSync } from "node:fs";
import { exec } from "./shell.js";
import {
  resolveStateBucket,
  resolveStateKey,
  resolveProfile,
  resolveRegion,
  resolveTerraformRoot,
  resolveTfvarsFile,
} from "./conventions.js";

export type TerraformAction = "apply" | "destroy" | "plan";

export type TerraformOptions = {
  root: string;
  stage: string;
  envName: string;
  type: "system" | "component";
  serviceName?: string;
  vars?: Record<string, string>;
  autoApprove?: boolean;
};

export type TerraformInitOptions = {
  root: string;
  stage: string;
  envName: string;
  type: "system" | "component";
  serviceName?: string;
};

function generateBackendFile(cwd: string, opts: TerraformInitOptions): void {
  const bucket = resolveStateBucket(opts.root, opts.stage);
  const key = resolveStateKey(opts.type, opts.envName, opts.serviceName);
  const region = resolveRegion(opts.root, opts.stage);
  const profile = resolveProfile(opts.root, opts.stage);

  writeFileSync(
    `${cwd}/_backend.tf`,
    `# Generated by ascli — do not edit
terraform {
  backend "s3" {
    bucket  = "${bucket}"
    key     = "${key}"
    region  = "${region}"
    profile = "${profile}"
  }
}
`,
  );
}

function generateProviderFile(cwd: string, opts: TerraformInitOptions): void {
  const region = resolveRegion(opts.root, opts.stage);
  const profile = resolveProfile(opts.root, opts.stage);

  writeFileSync(
    `${cwd}/_provider.tf`,
    `# Generated by ascli — do not edit
terraform {
  required_version = ">= 1.6"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.0"
    }
  }
}

provider "aws" {
  region  = "${region}"
  profile = "${profile}"
}
`,
  );
}

export function terraformInit(opts: TerraformInitOptions): void {
  const cwd = resolveTerraformRoot(opts.root, opts.type, opts.serviceName);

  generateBackendFile(cwd, opts);
  generateProviderFile(cwd, opts);

  exec("terraform init -reconfigure", { cwd });
}

function buildVars(opts: TerraformOptions): string[] {
  const vars: Record<string, string> = {
    stage: opts.stage,
    env_name: opts.envName,
    ...opts.vars,
  };

  return Object.entries(vars).map(([k, v]) => `-var=${k}=${v}`);
}

export function terraformRun(action: TerraformAction, opts: TerraformOptions): void {
  terraformInit(opts);

  const cwd = resolveTerraformRoot(opts.root, opts.type, opts.serviceName);
  const varArgs = buildVars(opts).join(" ");
  const approve = opts.autoApprove ? "-auto-approve" : "";
  const tfvarsFile = resolveTfvarsFile(cwd, opts.stage);
  const tfvarsArg = tfvarsFile ? `-var-file=${tfvarsFile}` : "";

  exec(`terraform ${action} ${tfvarsArg} ${varArgs} ${approve}`.trim(), { cwd });
}
