/**
 * TerraformEngine — implements IacEngine using Terraform CLI.
 *
 * Generates _backend.tf and _provider.tf from .as.yml conventions,
 * then runs terraform directly.
 */

import { writeFileSync } from "node:fs";
import { exec, execAsync } from "./shell.js";
import type { IacEngine, IacInitOpts, IacRunOpts } from "./engine.js";
import {
  resolveStateBucket,
  resolveStateKey,
  resolveProfile,
  resolveRegion,
  resolveIacRoot,
  resolveTfvarsFile,
} from "./conventions.js";

export class TerraformEngine implements IacEngine {
  readonly name = "terraform";

  init(opts: IacInitOpts): void {
    const cwd = resolveIacRoot(opts.root, opts.type, opts.serviceName);
    this.generateBackendFile(cwd, opts);
    this.generateProviderFile(cwd, opts);
    exec("terraform init -reconfigure", { cwd });
  }

  apply(opts: IacRunOpts): void {
    this.run("apply", opts);
  }

  destroy(opts: IacRunOpts): void {
    this.run("destroy", opts);
  }

  applyAsync(opts: IacRunOpts & { prefix?: string }): Promise<void> {
    return this.runAsync("apply", opts);
  }

  destroyAsync(opts: IacRunOpts & { prefix?: string }): Promise<void> {
    return this.runAsync("destroy", opts);
  }

  plan(opts: IacRunOpts): void {
    this.run("plan", opts);
  }

  private run(action: string, opts: IacRunOpts): void {
    this.init(opts);
    const cwd = resolveIacRoot(opts.root, opts.type, opts.serviceName);
    const varArgs = this.buildVars(opts).join(" ");
    const approve = opts.autoApprove ? "-auto-approve" : "";
    const tfvarsFile = resolveTfvarsFile(cwd, opts.stage);
    const tfvarsArg = tfvarsFile ? `-var-file=${tfvarsFile}` : "";
    exec(`terraform ${action} ${tfvarsArg} ${varArgs} ${approve}`.trim(), { cwd });
  }

  private async runAsync(action: string, opts: IacRunOpts & { prefix?: string }): Promise<void> {
    this.init(opts);
    const cwd = resolveIacRoot(opts.root, opts.type, opts.serviceName);
    const varArgs = this.buildVars(opts).join(" ");
    const approve = opts.autoApprove ? "-auto-approve" : "";
    const tfvarsFile = resolveTfvarsFile(cwd, opts.stage);
    const tfvarsArg = tfvarsFile ? `-var-file=${tfvarsFile}` : "";
    await execAsync(`terraform ${action} ${tfvarsArg} ${varArgs} ${approve}`.trim(), {
      cwd,
      prefix: opts.prefix,
    });
  }

  private buildVars(opts: IacRunOpts): string[] {
    const vars: Record<string, string> = {
      stage: opts.stage,
      env_name: opts.envName,
      ...opts.vars,
    };
    return Object.entries(vars).map(([k, v]) => `-var=${k}=${v}`);
  }

  private generateBackendFile(cwd: string, opts: IacInitOpts): void {
    const bucket = resolveStateBucket(opts.root, opts.stage);
    const key = resolveStateKey(opts.type, opts.envName, opts.serviceName);
    const region = resolveRegion(opts.root, opts.stage);
    const profile = resolveProfile(opts.root, opts.stage);

    writeFileSync(
      `${cwd}/_backend.tf`,
      `# Generated by ascli — do not edit
terraform {
  backend "s3" {
    bucket  = "${bucket}"
    key     = "${key}"
    region  = "${region}"
    profile = "${profile}"
  }
}
`,
    );
  }

  private generateProviderFile(cwd: string, opts: IacInitOpts): void {
    const region = resolveRegion(opts.root, opts.stage);
    const profile = resolveProfile(opts.root, opts.stage);

    writeFileSync(
      `${cwd}/_provider.tf`,
      `# Generated by ascli — do not edit
terraform {
  required_version = ">= 1.6"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.0"
    }
  }
}

provider "aws" {
  region  = "${region}"
  profile = "${profile}"
}
`,
    );
  }
}
